server:
  port: 8002
spring:
  application:
    name: server-consumer
  thymeleaf:
    cache: false  #关闭缓存
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
eureka:
  client:
    #register-with-eureka: false #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    prefer-ip-address: true     #访问路径可以显示IP地址
