server:
  port: 8082
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
spring:
  boot:
    admin:
      client:
        url: http://localhost:9004
  application:
    name: server-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
      sampler:
        probability: 1.0
#路由配置
zuul:
  routes:
    cart:
      path: /cart/**
      serviceId: server-cart
    portal:
      path: /portal/**
      serviceId: server-portal
    sellercenter:
      path: /sellercenter/**
      serviceId: server-sellercenter




