package com.ccit.dao;

import com.ccit.pojo.Shoes;

import java.util.List;


public interface ShoesMapper {
	
	List<Shoes> selectRand();
	List<Shoes> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoes
     *
     * @mbg.generated Sat Jun 01 16:54:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoes
     *
     * @mbg.generated Sat Jun 01 16:54:12 CST 2019
     */
    int insert(Shoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoes
     *
     * @mbg.generated Sat Jun 01 16:54:12 CST 2019
     */
    int insertSelective(Shoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoes
     *
     * @mbg.generated Sat Jun 01 16:54:12 CST 2019
     */
    Shoes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoes
     *
     * @mbg.generated Sat Jun 01 16:54:12 CST 2019
     */
    int updateByPrimaryKeySelective(Shoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoes
     *
     * @mbg.generated Sat Jun 01 16:54:12 CST 2019
     */
    int updateByPrimaryKey(Shoes record);
}